const images = {
  ArmenKhojoyan: require("./teamPhotos/ArmenKhojoyan.jpg"),
  ArmenYesoyan: require("./teamPhotos/ArmenYesoyan.jpg"),
  AniMkrtchyan: require("./teamPhotos/AniMkrtchyan.jpg"),
  AnjelaManukyan: require("./teamPhotos/AnjelaManukyan.jpg"),
  GurgenBadalyan: require("./teamPhotos/GurgenBadalyan.jpg"),
  VarduhiManukyan: require("./teamPhotos/VarduhiManukyan.jpg"),
  KhanumAbrahamyan: require("./teamPhotos/KhanumAbrahamyan.jpg"),
  RubikShahazizyan: require("./teamPhotos/RubikShahazizyan.jpg"),
  AnushTadevosyan: require("./teamPhotos/AnushTadevosyan.jpg"),
  DavitNikoghosyan: require("./teamPhotos/DavitNikoghosyan.jpg"),
  KoryunBznuni: require("./teamPhotos/KoryunBznuni.jpg"),
  ArmenAjamoghlyan: require("./teamPhotos/ArmenAjamoghlyan.jpg"),
  TorosTorosyan: require("./teamPhotos/TorosTorosyan.jpg"),
  GagikMelkonyan: require("./teamPhotos/GagikMelkonyan.jpg"),
  MargaritaGasparyan: require("./teamPhotos/MargaritaGasparyan.jpg"),
  LiaApikyan: require("./teamPhotos/LiaApikyan.jpg"),
  MilenaKiramijyan: require("./teamPhotos/MilenaKiramijyan.jpg"),
  SonaGalstyan: require("./teamPhotos/SonaGalstyan.jpg"),
  JannaDadiyan: require("./teamPhotos/JannaDadiyan.jpg"),
  AniTadevosyan: require("./teamPhotos/AniTadevosyan.jpg"),
  IrmaYuzbashyan: require("./teamPhotos/IrmaYuzbashyan.jpg"),
  HovhannesKarakhanyan: require("./teamPhotos/HovhannesKarakhanyan.jpg"),
  MikayelVardanyan: require("./teamPhotos/MikayelVardanyan.jpg"),
  AlbertArutunian: require("./teamPhotos/AlbertArutunian.jpg"),
  MisakHovakimyan: require("./teamPhotos/MisakHovakimyan.jpg"),
  LianaNersisyan: require("./teamPhotos/LianaNersisyan.jpg"),
  KarineMovsisyan: require("./teamPhotos/KarineMovsisyan.jpg"),
};

export default images;
