const images = {
  ArmenKhojoyan: require("./team/ArmenKhojoyan.jpg"),
  ArmenYesoyan: require("./team/ArmenYesoyan.jpg"),
  AniMkrtchyan: require("./team/AniMkrtchyan.jpg"),
  AnjelaManukyan: require("./team/AnjelaManukyan.jpg"),
  GurgenBadalyan: require("./team/GurgenBadalyan.jpg"),
  KhanumAbrahamyan: require("./team/KhanumAbrahamyan.jpg"),
  RubikShahazizyan: require("./team/RubikShahazizyan.jpg"),
  AnushTadevosyan: require("./team/AnushTadevosyan.jpg"),
  DavitNikoghosyan: require("./team/DavitNikoghosyan.jpg"),
  KoryunBznuni: require("./team/KoryunBznuni.jpg"),
  ArmenAjamoghlyan: require("./team/ArmenAjamoghlyan.jpg"),
  TorosTorosyan: require("./team/RubikShahazizyan.jpg"),
  GagikMelkonyan: require("./team/GagikMelkonyan.jpg"),
  MargaritaGasparyan: require("./team/MargaritaGasparyan.jpg"),
  LiaApikyan: require("./team/LiaApikyan.jpg"),
  MilenaKiramijyan: require("./team/MilenaKiramijyan.jpg"),
  SonaGalstyan: require("./team/SonaGalstyan.jpg"),
  JannaDadiyan: require("./team/JannaDadiyan.jpg"),
  AniTadevosyan: require("./team/AniTadevosyan.jpg"),
  IrmaYuzbashyan: require("./team/IrmaYuzbashyan.jpg"),
  HovhannesKarakhanyan: require("./team/HovhannesKarakhanyan.jpg"),
  MikayelVardanyan: require("./team/MikayelVardanyan.jpg"),
  AlbertArutunian: require("./team/AlbertArutunian.jpg"),
  MisakHovakimyan: require("./team/MisakHovakimyan.jpg"),
  LianaNersisyan: require("./team/LianaNersisyan.jpg"),
  KarineMovsisyan: require("./team/KarineMovsisyan.jpg"),
};

export default images;
