import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css";
import App from "./App";
import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import englishTranslations from './translations/english.json';
import {CssBaseline} from "@mui/material";

i18n.use(initReactI18next).init({
  resources: {
    en: englishTranslations,
    rus: {
      translation: {
        aboutUsLabel: "О нас",
        history: "История",
        ourCapabilities: "Наши возможности",
        ourPriorities: "Наши приоритеты",
        ourTeam: "Наша команда",
        ourPartners: "Наши партнеры",
        ourAchievements: "Наши достижения",
        accreditations: "Наши аккредитации",
        ourCapacities: "Оценка наших возможностей",
        projects: "Проекты",
        implementedProjects: "Реализованные проекты",
        currentProjects: "Текущие проекты",
        plannedProjects: "Планируемые проекты",
        results: "Результаты",
        projectStakeholders: "Бенефициары проектов",
        procurements: "Закупки",
        procurementForProjects: "Закупки для проектов",
        officeProcurement: "Закупки для БРЭП",
        announcements: "Объявления",
        news: "Ньюзрум",
        allNews: "Новости",
        pressAboutUs: "СМИ о Нас",
        mediaGallery: "Медиягалерея",
        contact: "Контакты",
        letterExample: "Пример письма",
        ourAddress: "Наш Адрес",
        contacts: "Контакты",
        hotline: "Горячая линия",
        contactWithUs: "Связаться с нами",
        street: "улица Арменакяна 129, Ереван",
        copyright: "Copyright © 2022 Все права защищены.",
        contactName: "Имя",
        contactEmail: "Адрес электронной почты",
        contactMessage: "Сообщение",
        placeholderName: "Ваше имя",
        placeholderEmail: "Ваш адрес электронной почты",
        placeholderMessage: "Ваше сообщение",
        button: "Отправить",
        pText: "Горячая линия работает каждый рабочий день с 09:00 до 18:00.",
        title: "Контактная информация",
        ourTeamHead: "Армен Есоян",
        headPosition: "Исполняющий обязанности директора",
        viewBio: "Просмотреть биографию",
        ourTeamHead2: "Армен Ходжоян",
        headPosition2: "Исполняющий обязанности заместителя директора",
        teamName: "Административный и обслуживающий персонал",
        member1: "Ани Мкртчян",
        member1Position: "Исполняющий обязанности юриста",
        member2: "Анжела Манукян",
        member3: "Гурген Бадалян",
        member4: "Вардуи Манукян",
        member5: "Ханум Абраамян",
        member2Position: "Исполняющий обязанности главного бухгалтера",
        member3Position: "Исполняющий обязанности бухгалтера",
        member4Position: "Ответственный по документообороту",
        member5Position: "Уборщица",
        teamName2: "Отдел реализации и мониторинга проектов",
        teamName2Member1: "Рубик Шаазизян",
        teamName2Member2: "Ануш Тадевосян",
        teamName2Member3: "Давит Никогосян ",
        teamName2Member4: "Корюн Бзуни",
        teamName2Member5: "Армен Аджамоглян",
        teamName2Member6: "Торос Торосян",
        teamName2Member7: "Гагик Мелконян",
        teamName2Member1Position: "Исполняющий обязанности руководителя отдела",
        teamName2Position: "Исполняющий обязанности главного специалиста",
        teamName2Member6Position:
          "Исполняющий обязанности ведущего специалиста",
        teamName2Member7Position:
          "Исполняющий обязанности специалиста первого класса",
        teamName3: "Отдел сотрудничества с донорами",
        teamName3Member1: "Маргарита Гаспарян",
        teamName3Member2: "Лия Апикян",
        teamName3Member3: "Грета Макунц",
        teamName3Member4: "Милена Кирамиджян",
        teamName3Member5: "Сона Галстян",
        teamName3Member1Position: "Исполняющий обязанности руководителя отдела",
        teamName3Member2Position:
          "Исполняющий обязанности главного специалиста",
        teamName3Member3Position:
          "Исполняющий обязанности ведущего специалиста",
        teamName3Member4Position:
          "Исполняющий обязанности ведущего специалиста",
        teamName3Member5Position:
          "Исполняющий обязанности специалиста первого класса",
        teamName4: "Отдел по административным вопросам и закупкам",
        teamName4Member1: "Жанна Дадиян",
        teamName4Member2: "Ани Тадевосян",
        teamName4Member3: "Ирма Юзбашян",
        teamName4Member4: "Ованнес Караханян",
        teamName4Member5: "Микаел Варданян",
        teamName4Member1Position: "Исполняющий обязанности руководителя отдела",
        teamName4Member2Position:
          "Исполняющий обязанности главного специалиста",
        teamName4Member3Position:
          "Исполняющий обязанности специалиста первого класса",
        experts: "Эксперты",
        expert1: "Альберт Арутюнян",
        expert2: "Мисак Овакимян",
        expert3: "Лиана Нерсисян",
        expert4: "Карине Мовсисян",
      },
    },
    arm: {
      translation: {
        aboutUsLabel: "Մեր մասին",
        history: "Պատմություն",
        ourCapabilities: "Մեր կարողությունները",
        ourPriorities: "Մեր առաջնահերթությունները",
        ourTeam: "Մեր թիմը",
        ourPartners: "Մեր գործընկերները",
        ourAchievements: "Մեր ձեռքբերումները",
        accreditations: "Մեր հավատարմագրումները",
        ourCapacities: "Մեր կարողությունների գնահատումները",
        projects: "Ծրագրեր",
        implementedProjects: "Իրականացված",
        currentProjects: "Ընթացիկ",
        plannedProjects: "Նախատեսվող",
        results: "Արդյունքներ",
        projectStakeholders: "Շահառուներ",
        procurements: "Գնումներ",
        procurementForProjects: "Ծրագրերի շրջանակներում իրականացվող գնումներ",
        officeProcurement: "Գնումներ գրասենյակի կարիքների համար",
        announcements: "Հայտարարություններ",
        news: "Նորություններ",
        allNews: "Լրահոս",
        pressAboutUs: "Մամուլը մեր մասին",
        mediaGallery: "Տեսադարան",
        contact: "Կապ",
        letterExample: "Նամակի ձև",
        ourAddress: "Մեր հասցեն",
        contacts: "Կոնտակտներ",
        hotline: "Թեժ գիծ",
        contactWithUs: "Կապ մեզ հետ",
        street: "Արմենակյան 129, Երևան",
        copyright:
          "Հեղինակային իրավունք @2022 Բոլոր իրավունքները պաշտպանված են:",
        contactName: "Անուն",
        contactEmail: "Էլեկտրոնային հասցե",
        contactMessage: "Հաղորդագրություն",
        placeholderName: "Ձեր անունը",
        placeholderEmail: "Ձեր էլ. փոստի հասցեն",
        placeholderMessage: "Ձեր հաղորդագրությունը",
        button: "Ուղարկել",
        pText:
          "Թեժ գիծը հասանելի է յուրաքանչյուր աշխատանքային օր՝ ժամը 09։00-18։00:",
        title: "Կոնտակտային տվյալներ",
        ourTeamHead: "Արմեն Եսոյան",
        headPosition: "Տնօրենի պաշտոնակատար",
        viewBio: "Դիտել կենսագրությունը",
        ourTeamHead2: "Արմեն Խոջոյան",
        headPosition2: "Տնօրենի տեղակալ պաշտոնակատար",
        teamName: "Վարչական և սպասարկման անձնակազմ",
        member1: "Անի Մկրտչյան",
        member1Position: "Իրավաբանի պաշտոնակատար",
        member2: "Անժելա Մանուկյան ",
        member3: "Գուրգեն Բադալյան",
        member4: "Վարդուհի Մանուկյան ",
        member5: "Խանում Աբրահամյան ",
        member2Position: "Գլխավոր հաշվապահի պաշտոնակատար",
        member3Position: "Հաշվապահի պաշտոնակատար",
        member4Position: "Փաստաթղթաշրջանառության պատասխանատու",
        member5Position: "Հավաքարար",
        teamName2: "Ծրագրերի իրականացման և մոնիթորինգի բաժին",
        teamName2Member1: "Ռուբիկ Շահազիզյան ",
        teamName2Member2: "Անուշ Թադևոսյան",
        teamName2Member3: "Դավիթ Նիկողոսյան ",
        teamName2Member4: "Կորյուն Բզնունի",
        teamName2Member5: "Արմեն Աջամօղլյան",
        teamName2Member6: "Թորոս Թորոսյան",
        teamName2Member7: "Գագիկ Մելքոնյան",
        teamName2Member1Position: "Բաժնի պետի պաշտոնակատար",
        teamName2Position: "Գլխավոր մասնագետի պաշտոնակատար",
        teamName2Member6Position: "Առաջատար մասնագետի պաշտոնակատար",
        teamName2Member7Position: "Առաջին կարգի մասնագետի պաշտոնակատար",
        teamName3: "Դոնորների հետ համագործակցության բաժին",
        teamName3Member1: "Մարգարիտա Գասպարյան",
        teamName3Member2: "Լիա Ապիկյան",
        teamName3Member3: "Գրետա Մակունց",
        teamName3Member4: "Միլենա Քիրամիջյան",
        teamName3Member5: "Սոնա Գալստյան",
        teamName3Member1Position: "Բաժնի պետի պաշտոնակատար",
        teamName3Member2Position: "Գլխավոր մասնագետի պաշտոնակատար",
        teamName3Member3Position: "Առաջատար մասնագետի պաշտոնակատար",
        teamName3Member4Position: "Առաջատար մասնագետի պաշտոնակատար",
        teamName3Member5Position: "Առաջին կարգի մասնագետի պաշտոնակատար",
        teamName4: "Գործերի կառավարման և գնումների",
        teamName4Member1: "Ժաննա Դադիյան",
        teamName4Member2: "Անի Թադևոյան",
        teamName4Member3: "Իռմա Յուզբաշյան",
        teamName4Member4: "Հովհաննես Կարախանյան",
        teamName4Member5: "Միքայել Վարդանյան",
        teamName4Member1Position: "Բաժնի պետի պաշտոնակատար",
        teamName4Member2Position: "Գլխավոր մասնագետի պաշտոնակատար",
        teamName4Member3Position: "Առաջին կարգի մասնագետի պաշտոնակատար",
        experts: "Փորձագետներ",
        expert1: "Ալբերտ Հարությունյան",
        expert2: "Միսակ Հովակիմյան",
        expert3: "Լիանա Ներսիսյան",
        expert4: "Կարինե Մովսիսյան",
      },
    },
  },
  lng: "en", // if you're using a language detector, do not define the lng option
  fallbackLng: "en",
  interpolation: {
    escapeValue: false, // react already safes from xss => https://www.i18next.com/translation-function/interpolation#unescape
  },
});

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(
  <React.StrictMode>
    <CssBaseline />
    <App />
  </React.StrictMode>
);
